version: '3.7'
services:
  resqu:
    image: pyrooka/resqu:latest
    restart: always
    environment:
      - SERVER_PORT=8888
    volumes:
      - ./config.yaml:/resqu/config.yaml
      - ./employees.sqlite3:/db/employees.sqlite3
    ports:
      - "8080:8888"